project_id = "oknnklksdiqaifhxaccs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://preview--smallchops-09.lovable.app"
additional_redirect_urls = ["https://preview--smallchops-09.lovable.app", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_email_autoconfirm = false
enable_phone_confirmations = false
enable_phone_autoconfirm = false

[functions.enhanced-smtp-sender]
verify_jwt = false

[functions.instant-email-processor]
verify_jwt = false

[functions.instant-welcome-processor]
verify_jwt = false

[functions.smtp-email-sender]
verify_jwt = true

[functions.smtp-health-monitor]
verify_jwt = false

[functions.production-email-processor]
verify_jwt = false

[functions.paystack-secure]
verify_jwt = false

[functions.process-checkout]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook-secure]
verify_jwt = false

[functions.unsubscribe-email]
verify_jwt = false

[functions.paystack-health]
verify_jwt = false

[functions.paystack-batch-verify]
verify_jwt = true

[functions.payment-reconcile]
verify_jwt = true

[functions.paystack-webhook-test]
verify_jwt = true
