project_id = "oknnklksdiqaifhxaccs"

[functions.admin-orders-manager]
verify_jwt = true

[functions.process-checkout]
verify_jwt = false

[functions.production-error-handler]
verify_jwt = false

[functions.reports]
verify_jwt = true

[functions.simplified-product-upload]
verify_jwt = true