project_id = "oknnklksdiqaifhxaccs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://startersmallchops.com"
additional_redirect_urls = ["https://startersmallchops.com/auth/callback", "https://startersmallchops.com/email-verification"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "https://oknnklksdiqaifhxaccs.supabase.co/auth/v1/callback"

[functions.secure-payment-processor]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.enhanced-smtp-sender]
verify_jwt = false

[functions.instant-email-processor]
verify_jwt = false

[functions.instant-welcome-processor]
verify_jwt = false

[functions.smtp-email-sender]
verify_jwt = true

[functions.supabase-auth-email-sender]
verify_jwt = false

[functions.smtp-health-monitor]
verify_jwt = false

[functions.production-email-processor]
verify_jwt = false

[functions.paystack-secure]
verify_jwt = false

[functions.process-checkout]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook-secure]
verify_jwt = false

[functions.unsubscribe-email]
verify_jwt = false

[functions.paystack-health]
verify_jwt = false

[functions.paystack-batch-verify]
verify_jwt = true

[functions.payment-reconcile]
verify_jwt = true

[functions.paystack-webhook-test]
verify_jwt = true

[functions.production-paystack-setup]
verify_jwt = true

[functions.admin-management]
verify_jwt = false

[functions.reports]
verify_jwt = false

[functions.get-turnstile-key]
verify_jwt = false

[functions.payment-health-check]
verify_jwt = false

[functions.welcome-email-queue-processor]
verify_jwt = false
