project_id = "oknnklksdiqaifhxaccs"

[functions.admin-orders-manager]
verify_jwt = true

[functions.paystack-secure]
verify_jwt = false

[functions.process-checkout]
verify_jwt = false

[functions.production-error-handler]
verify_jwt = false

[functions.reports]
verify_jwt = true

[functions.simplified-product-upload]
verify_jwt = true

[functions.admin-management]
verify_jwt = true

[functions.admin-order-notification]
verify_jwt = false

[functions.unified-smtp-sender]
verify_jwt = false

[functions.process-communication-events-enhanced]
verify_jwt = false

[functions.payment-confirmation-processor]
verify_jwt = false

[functions.enhanced-email-rate-limiter]
verify_jwt = false

[functions.enhanced-email-retry]
verify_jwt = false